apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::954741360889:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NY0UAU79B0I5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::954741360889:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-30T16:48:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "825"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ec8cb272-d395-40ac-a855-7cf934dc28ec
