apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::954741360889:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
         - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::954741360889:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BXGALULIBHC4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-29T09:21:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4805"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5a3bacab-032e-4cb4-9ab2-60b37a76f3a0
